version = 0.1
[default.deploy.parameters]
stack_name = "nuxt-testing-deploy"
resolve_s3 = true
s3_prefix = "nuxt-testing-deploy"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"$default\""
image_repositories = []
disable_rollback = true
