name: SSH and Redeploy on Server

on:
  registry_package:
    types:
      - published
      - updated
jobs:
  deploy-on-server:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to Tailnet
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          
      - name: SSH into server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            ls -a
